reuters: http://feeds.reuters.com/reuters/UKTopNews
#bbc_news: http://feeds.bbci.co.uk/news/uk/rss.xml
#daily_mail: feed://www.dailymail.co.uk/home/index.rss
#guardian: https://www.theguardian.com/uk/rss
#independent: http://www.independent.co.uk/news/uk/rss